"""BI-PF-1206 (C4): compliance register - validate + render, and verify IMPLEMENTED controls resolve evidence.

SSOT: config/compliance-register.json (framework -> control -> owner -> status -> evidence). Renders
docs/COMPLIANCE-REGISTER.md. ``--check`` FAILS when a control marked ``status=implemented`` has evidence that does
not resolve. Gaps are reported (advisory). Wired into precheck.
"""
import argparse
import json
import os
import sys

try:
    from core.paths import ROOT as _ROOT
except ImportError:
    _ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

REG = os.path.join(_ROOT, "config", "compliance-register.json")
OUT = os.path.join(_ROOT, "docs", "COMPLIANCE-REGISTER.md")
_STATUS = ("implemented", "partial", "gap")


def _load() -> dict:
    with open(REG, encoding="utf-8") as f:
        return json.load(f)


def _gate_names() -> set:
    names = set()
    try:
        pp = os.path.join(_ROOT, "scripts", "dev", "precheck.py")
        import re
        for ln in open(pp, encoding="utf-8"):
            m = re.match(r'\s*\(\s*"([a-z0-9\-]+)"\s*,', ln)
            if m:
                names.add(m.group(1))
    except Exception:
        pass
    return names


def _evidence_ok(ev: str, gates) -> bool:
    if not ev:
        return False
    if ev.startswith("gate:"):
        return ev.split(":", 1)[1] in gates
    return os.path.exists(os.path.join(_ROOT, ev))


def validate(reg: dict) -> list:
    probs, gates = [], _gate_names()
    for fw, controls in (reg.get("frameworks") or {}).items():
        if not controls:
            probs.append(f"{fw}: no controls")
        for c in controls:
            cid = c.get("id")
            if not cid:
                probs.append(f"{fw}: control without id")
            if c.get("status") not in _STATUS:
                probs.append(f"{cid}: invalid status {c.get('status')!r}")
            if c.get("status") == "implemented" and not _evidence_ok(c.get("evidence", ""), gates):
                probs.append(f"{cid}: status=implemented but evidence does not resolve ({c.get('evidence')!r})")
    return probs


def render(reg: dict) -> str:
    lines = ["# Compliance Register (generated)", "",
             "> Generated by `scripts/dev/compliance_register_check.py` from `config/compliance-register.json`.",
             "> **Do not edit by hand.** status: implemented | partial | gap.", ""]
    for fw, controls in (reg.get("frameworks") or {}).items():
        lines += [f"## {fw}", "", "| Control | Owner | Status | Evidence |", "|---|---|---|---|"]
        for c in controls:
            lines.append(f"| {c.get('id')} - {c.get('control')} | {c.get('owner')} | {c.get('status')} | "
                         f"`{c.get('evidence') or '-'}` |")
        lines.append("")
    lines += ["## Claims policy", "", reg.get("claims_policy", ""), ""]
    return "\n".join(lines)


def _current() -> str:
    try:
        return open(OUT, encoding="utf-8").read()
    except Exception:
        return ""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)
    reg = _load()
    probs = validate(reg)
    if probs:
        print(f"compliance-register: FAIL ({len(probs)} problem(s))")
        for p in probs[:20]:
            print("   -", p)
        return 1
    doc = render(reg)
    if a.write:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(doc)
        print(f"compliance-register: wrote {os.path.relpath(OUT, _ROOT)}")
        return 0
    if a.check and doc.strip() != _current().strip():
        print("compliance-register: FAIL - docs/COMPLIANCE-REGISTER.md stale; run: "
              "python scripts/dev/compliance_register_check.py --write")
        return 1
    gaps = sum(1 for ctrls in (reg.get("frameworks") or {}).values()
               for c in ctrls if c.get("status") == "gap")
    print(f"compliance-register: OK (evidence resolves; {gaps} documented gap(s) - see docs/COMPLIANCE-REGISTER.md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
