"""BI-PF-0765 - render docs/ARTIFACT-OWNERS.md from config/artifact-owners.json (single source of truth).

Validates every owner/consumer against core.agent_structure.KNOWN_AGENTS, then renders the artifact table +
pipeline order. ``--check`` fails when the committed doc is stale (regenerate with ``--write``). Wired into precheck.
"""
import argparse
import json
import os
import sys

try:
    from core.paths import ROOT as _ROOT
except ImportError:
    _ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

REG = os.path.join(_ROOT, "config", "artifact-owners.json")
OUT = os.path.join(_ROOT, "docs", "ARTIFACT-OWNERS.md")


def known_agents() -> set:
    """The authoritative agent set = the agent cards in agents/*.agent.json (not the stale KNOWN_AGENTS list)."""
    d = os.path.join(_ROOT, "agents")
    out = set()
    for f in os.listdir(d) if os.path.isdir(d) else []:
        if f.endswith(".agent.json"):
            out.add(f[: -len(".agent.json")])
    return out


def _load() -> dict:
    with open(REG, encoding="utf-8") as f:
        return json.load(f)


def validate(reg: dict) -> list:
    probs = []
    known = known_agents()
    for a in reg.get("artifacts", []):
        if not a.get("owner"):
            probs.append(f"{a.get('name')}: missing owner")
        elif a["owner"] not in known:
            probs.append(f"{a.get('name')}: owner {a['owner']!r} is not a known agent")
        for c in a.get("consumers") or []:
            if c not in known:
                probs.append(f"{a.get('name')}: consumer {c!r} is not a known agent")
    return probs


def render(reg: dict) -> str:
    lines = [
        "# Artifact → Owner agent → Consumers (generated)",
        "",
        "> Generated by `scripts/dev/gen_artifact_map.py` from `config/artifact-owners.json` "
        "(the single source of truth). **Do not edit by hand.**",
        "",
        "| Artifact | Path | Owner agent | Consumers (next) | Phase | Purpose |",
        "|---|---|---|---|---|---|",
    ]
    for a in reg.get("artifacts", []):
        lines.append(f"| {a.get('name')} | `{a.get('path')}` | **{a.get('owner')}** | "
                     f"{', '.join(a.get('consumers') or [])} | {a.get('phase', '')} | {a.get('purpose', '')} |")
    order = reg.get("pipeline_order") or []
    lines += ["", "## Pipeline order (who hands off to whom)", "", "`" + " → ".join(order) + "`", ""]
    return "\n".join(lines)


def _current() -> str:
    try:
        with open(OUT, encoding="utf-8") as f:
            return f.read()
    except Exception:
        return ""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if docs/ARTIFACT-OWNERS.md is stale")
    ap.add_argument("--write", action="store_true", help="regenerate docs/ARTIFACT-OWNERS.md")
    a = ap.parse_args(argv)
    reg = _load()
    probs = validate(reg)
    if probs:
        print(f"artifact-map: FAIL ({len(probs)} validation problem(s))")
        for p in probs[:20]:
            print("   -", p)
        return 1
    doc = render(reg)
    if a.write:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(doc)
        print(f"artifact-map: wrote {os.path.relpath(OUT, _ROOT)} ({len(reg.get('artifacts', []))} artifacts)")
        return 0
    if a.check and doc.strip() != _current().strip():
        print("artifact-map: FAIL - docs/ARTIFACT-OWNERS.md is stale; run: python scripts/dev/gen_artifact_map.py --write")
        return 1
    print(f"artifact-map: OK ({len(reg.get('artifacts', []))} artifacts, owners/consumers valid)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
