"""BI-PF-1066 - render docs/REVIEW-FOCUS.md from config/review-focus.json (single source of truth) + validate it.

The code-review agent consumes this checklist (per build iteration). ``--check`` fails when the committed doc is
stale. Wired into precheck.
"""
import argparse
import json
import os
import sys

try:
    from core.paths import ROOT as _ROOT
except ImportError:
    _ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

REG = os.path.join(_ROOT, "config", "review-focus.json")
OUT = os.path.join(_ROOT, "docs", "REVIEW-FOCUS.md")


def _load() -> dict:
    with open(REG, encoding="utf-8") as f:
        return json.load(f)


def validate(reg: dict) -> list:
    probs = []
    if not reg.get("severity"):
        probs.append("missing severity policy")
    seen = set()
    for c in reg.get("categories", []):
        cid = c.get("id")
        if not cid:
            probs.append("category without id")
        elif cid in seen:
            probs.append(f"duplicate category id {cid!r}")
        seen.add(cid)
        if c.get("stage") not in ("review", "design", "architect"):
            probs.append(f"{cid}: invalid stage {c.get('stage')!r}")
        if not (c.get("checks") or []):
            probs.append(f"{cid}: no checks")
    for key in ("always_flag", "ignore"):
        if not isinstance(reg.get(key), list):
            probs.append(f"{key} must be a list")
    return probs


def render(reg: dict) -> str:
    sev = reg.get("severity", {})
    lines = [
        "# Review Focus (generated)",
        "",
        "> Generated by `scripts/dev/gen_review_focus.py` from `config/review-focus.json` (single source of truth).",
        "> **Do not edit by hand.** Consumed by the code-review agent, which runs **per build iteration**.",
        "",
        "## Severity policy",
        "",
        "| Severity | Action |",
        "|---|---|",
    ]
    for k, v in sev.items():
        lines.append(f"| {k} | {v} |")
    lines += ["", "**ALWAYS flag** (high severity): " + ", ".join(reg.get("always_flag", [])),
              "", "**IGNORE** (defer to lint): " + ", ".join(reg.get("ignore", [])), ""]
    for stage, heading in (("review", "Reviewer checks (code-review agent)"),
                           ("design", "Shift-left: design/spec gate (E6)"),
                           ("architect", "Shift-left: architecture/contract gate (E7)")):
        cats = [c for c in reg.get("categories", []) if c.get("stage") == stage]
        if not cats:
            continue
        lines += [f"## {heading}", "", "| Category | Checks |", "|---|---|"]
        for c in cats:
            lines.append(f"| **{c.get('title')}** | " + "; ".join(c.get("checks", [])) + " |")
        lines.append("")
    return "\n".join(lines)


def _current() -> str:
    try:
        with open(OUT, encoding="utf-8") as f:
            return f.read()
    except Exception:
        return ""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)
    reg = _load()
    probs = validate(reg)
    if probs:
        print(f"review-focus: FAIL ({len(probs)} validation problem(s))")
        for p in probs[:20]:
            print("   -", p)
        return 1
    doc = render(reg)
    if a.write:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(doc)
        print(f"review-focus: wrote {os.path.relpath(OUT, _ROOT)} ({len(reg.get('categories', []))} categories)")
        return 0
    if a.check and doc.strip() != _current().strip():
        print("review-focus: FAIL - docs/REVIEW-FOCUS.md is stale; run: python scripts/dev/gen_review_focus.py --write")
        return 1
    print(f"review-focus: OK ({len(reg.get('categories', []))} categories)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
