#!/usr/bin/env python3
"""
Generate docs/modelanalysis.md — capability analysis of all models (our registry
across all providers + live OpenRouter/Zen metadata) and per-tier recommendations
for operating all agents.

Data sources:
  - products/.pipeline/model_registry.json        (our registry: provider/tier/cost/context/caps)
  - https://openrouter.ai/api/v1/models           (real: ctx, maxout, modality, supported_parameters)
  - https://opencode.ai/zen/v1/models             (live Zen model list)
  - agents/*.agent.json                            (what agents need: tools, role)
  - docs/zen pricing (embedded)                   (Zen per-1M pricing)
"""
try:
    from core.paths import ROOT as _PF_ROOT
except ImportError:  # executed as a script: seed the repo root on sys.path, then retry
    import os as _pf_os
    import sys as _pf_sys
    _pf_d = _pf_os.path.abspath(__file__)
    for _pf_i in range(3):
        _pf_d = _pf_os.path.dirname(_pf_d)
        if _pf_os.path.isfile(_pf_os.path.join(_pf_d, 'core', 'paths.py')):
            _pf_sys.path.insert(0, _pf_d)
            break
    from core.paths import ROOT as _PF_ROOT

import glob
import json
import os
import urllib.request
from datetime import datetime

ROOT = str(_PF_ROOT)
OUT = os.path.join(ROOT, "docs", "modelanalysis.md")
REGISTRY = os.path.join(ROOT, "products", ".pipeline", "model_registry.json")

try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(ROOT, ".env"))
except Exception:
    pass


def _get(url, key_env=""):
    headers = {"User-Agent": "model-analysis/1.0"}
    if key_env:
        k = os.getenv(key_env, "")
        if k:
            headers["Authorization"] = "Bearer " + k
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return json.loads(r.read().decode())
    except Exception as e:
        print("fetch failed", url, e)
        return {}


def load_registry():
    if os.path.exists(REGISTRY):
        return json.load(open(REGISTRY, encoding="utf-8")).get("models", [])
    return []


def load_agents():
    agents = []
    for f in sorted(glob.glob(os.path.join(ROOT, "agents", "*.agent.json"))):
        try:
            d = json.load(open(f, encoding="utf-8"))
        except Exception:
            continue
        agents.append({
            "id": d.get("id") or os.path.basename(f).replace(".agent.json", ""),
            "tools": d.get("tools") or [],
            "desc": (d.get("description") or "").strip(),
        })
    return agents


# OpenCode Zen pricing (from docs, per 1M tokens) — free models first
ZEN_PRICING = {
    "big-pickle": (0, 0), "mimo-v2.5-free": (0, 0), "ling-3.0-flash-fin-free": (0, 0),
    "nemotron-3-ultra-free": (0, 0), "nemotron-3.5-lightning-free": (0, 0),
    "muse-spark-1.3-contributor-free": (0, 0),
    "qwen3.8-flash": (0.15, 0.47), "deepseek-v4-flash": (0.14, 0.28),
    "glm-5.3-flash": (0.15, 0.50), "qwen3.5-plus": (0.20, 1.20),
    "gpt-5.6-luna": (0.20, 1.20), "minimax-m3": (0.30, 1.20),
    "qwen3.7-plus": (0.40, 1.60), "kimi-k2.6": (0.95, 4.00),
    "kimi-k2.7-code": (0.95, 4.00), "deepseek-v4-pro": (1.74, 3.48),
    "glm-5": (1.00, 3.20), "glm-5.2": (1.40, 4.40), "glm-5.3": (1.40, 4.40),
    "qwen3.6-plus": (0.50, 3.00), "qwen3.7-max": (2.50, 7.50),
    "kimi-k3": (3.00, 15.00), "claude-sonnet-5": (2.00, 10.00),
    "claude-haiku-4-5": (1.00, 5.00), "claude-opus-5": (5.00, 25.00),
    "gemini-3.5-flash": (1.50, 9.00), "gemini-3.5-flash-lite": (0.30, 2.50),
    "gemini-3-flash": (0.50, 3.00), "grok-4.6": (2.00, 6.00), "grok-4.5": (2.00, 6.00),
    "gpt-5.5": (5.00, 30.00), "gpt-5.4-mini": (0.75, 4.50), "gpt-5-nano": (0.05, 0.40),
}


def fetch_or_models():
    data = _get("https://openrouter.ai/api/v1/models", "OPENROUTER_API_KEY")
    return data.get("data", [])


def fetch_zen_models():
    data = _get("https://opencode.ai/zen/v1/models", "OPENCODE_ZEN_API_KEY")
    return [m.get("id") for m in data.get("data", [])]


def caps_from_registry(m):
    return {c for c in (m.get("capabilities") or [])}


def or_params(m):
    params = set(m.get("supported_parameters") or [])
    arch = m.get("architecture") or {}
    modal = set(arch.get("input_modalities") or [])
    return params, modal


def fmt_cost(a, b):
    if a is None:
        return "?"
    if a == 0 and b == 0:
        return "free"
    return f"${a}/${b}"


def main():
    reg = load_registry()
    agents = load_agents()
    or_models = fetch_or_models()
    zen_ids = fetch_zen_models()
    by_id = {m.get("id"): m for m in or_models}

    def or_for(name):
        if name in by_id:
            return by_id[name]
        for mid, m in by_id.items():
            if mid.split("/")[-1] == name or mid.endswith(name):
                return m
        return None

    L = []
    A = L.append
    A("# Model Analysis — Capabilities & Tier Recommendations")
    A("")
    A(f"> Auto-generated by `scripts/dev/generate_model_analysis.py` on {datetime.now().isoformat(timespec='seconds')}.")
    A("> Sources: our model registry, OpenRouter `/models` (real capability metadata),")
    A("> OpenCode Zen live model list + docs pricing, `agents/*.agent.json`.")
    A("")
    A("## 1. Purpose")
    A("Pick the right model per agent and per cost tier, based on **capabilities that matter for")
    A("agents**: function/tool calling, reasoning, structured output, context/output size, and modalities.")
    A("")
    A("## 2. Capability legend")
    A("| Tag | Meaning |")
    A("|---|---|")
    A("| **T** | tool / function calling |")
    A("| **R** | reasoning (chain-of-thought / thinking) |")
    A("| **S** | structured outputs / JSON response_format |")
    A("| **V** | vision (image input) |")
    A("| **A** | audio input |")
    A("| **1M** | ≥ 1,000,000 token context |")
    A("")
    A("## 3. What the agents need")
    A("| Agent | Tools | Role (from spec) |")
    A("|---|---|---|")
    for a in agents:
        A(f"| {a['id']} | {len(a['tools'])} | {a['desc'][:70]} |")
    A("")
    tools_agents = [a["id"] for a in agents if a["tools"]]
    A(f"**Tool-using agents ({len(tools_agents)}):** {', '.join(tools_agents)} — these **require `T`**.")
    A("All planning/review/docs agents benefit from **`R`**; design/visual_qa/content-reader benefit from **`V`**.")
    A("")

    # OpenRouter free
    A("## 4. OpenRouter — free models (real metadata)")
    free_or = [m for m in or_models if str((m.get("pricing") or {}).get("prompt")) == "0"
               and str((m.get("pricing") or {}).get("completion")) == "0"]
    A("| Model | Ctx | MaxOut | T | R | S | Modality |")
    A("|---|---|---|---|---|---|---|")
    for m in sorted(free_or, key=lambda x: x.get("id", "")):
        params, modal = or_params(m)
        top = m.get("top_provider") or {}
        A("| `%s` | %s | %s | %s | %s | %s | %s |" % (
            m.get("id"), m.get("context_length"), top.get("max_completion_tokens"),
            "Y" if "tools" in params else "-", "Y" if "reasoning" in params else "-",
            "Y" if ("structured_outputs" in params or "response_format" in params) else "-",
            "+".join(sorted(modal)) or "text"))
    A("")

    # OpenRouter frontier paid
    A("## 5. OpenRouter — frontier paid (tools + reasoning, by context)")
    paid = [m for m in or_models
            if str((m.get("pricing") or {}).get("prompt")) not in ("0", "None")
            and "tools" in set(m.get("supported_parameters") or [])]
    paid = sorted(paid, key=lambda m: -(m.get("context_length") or 0))[:30]
    A("| Model | Ctx | MaxOut | $in/$out per 1M | R | V |")
    A("|---|---|---|---|---|---|")
    for m in paid:
        params, modal = or_params(m)
        p = m.get("pricing") or {}
        A("| `%s` | %s | %s | %s | %s | %s |" % (
            m.get("id"), m.get("context_length"),
            (m.get("top_provider") or {}).get("max_completion_tokens"),
            fmt_cost(p.get("prompt"), p.get("completion")),
            "Y" if "reasoning" in params else "-", "Y" if "image" in modal else "-"))
    A("")

    # OpenCode Zen
    A("## 6. OpenCode Zen — live models (docs pricing, $/1M)")
    A("| Model | Provider | $in/$out | Notes |")
    A("|---|---|---|---|")
    for mid in sorted(zen_ids):
        if mid in ZEN_PRICING:
            c = ZEN_PRICING[mid]
            note = "FREE" if c == (0, 0) else ""
        else:
            c = ("?", "?")
            note = ""
        A(f"| `{mid}` | opencode-go | {fmt_cost(*c) if c[0] != '?' else '?'} | {note} |")
    A("")

    # Registry appendix
    A("## 7. Registry — all models by provider (our catalog)")
    A("Fields: tier · $in/$out per 1k · context · capability tags (from registry).")
    by_prov = {}
    for m in reg:
        by_prov.setdefault(m.get("provider", "?"), []).append(m)
    for prov in sorted(by_prov):
        A(f"### {prov} ({len(by_prov[prov])})")
        A("| Model | Tier | $in/$out per 1k | Ctx | Caps |")
        A("|---|---|---|---|---|")
        for m in sorted(by_prov[prov], key=lambda x: x.get("name", "")):
            A("| `%s` | %s | %s/%s | %s | %s |" % (
                m.get("name"), m.get("tier"), m.get("cost_per_1k_input"),
                m.get("cost_per_1k_output"), m.get("context_window"),
                ",".join(m.get("capabilities") or [])))
        A("")

    # Recommendations
    A("## 8. Recommendations by tier")
    A("")
    A("### 8.1 Premium (paid — best quality)")
    A("- **Reasoning/architecture:** `claude-opus-5` / `gpt-5.6-sol` (Zen) or OpenRouter `anthropic/claude-opus-*`, `openai/gpt-5.*`.")
    A("- **Code:** `kimi-k2.7-code`, `deepseek-v4-pro` (Zen) or `qwen3.8-max`.")
    A("- **Balanced:** `claude-sonnet-5`, `gpt-5.5`.")
    A("- Requirements: tools + reasoning + large context. Use for `architect`, `implement`, `code-review`, `security`.")
    A("")
    A("### 8.2 Cheap paid (budget, still capable)")
    A("- **Workhorse:** `deepseek-v4-flash` ($0.14/$0.28), `qwen3.8-flash`, `glm-5.3-flash`.")
    A("- **Cheap code:** `cohere/north-mini-code`, `poolside/laguna`, `deepseek-v4-flash`.")
    A("- **Cheap docs/analysis:** `gemini-3.5-flash-lite`, `gpt-5-nano`, `gpt-5.4-mini`.")
    A("")
    A("### 8.3 OpenCode Go (paid, unified endpoint)")
    A("- **Planner/reasoner:** `mimo-v2.5-pro`, `gpt-5.6-luna`; **code:** `kimi-k2.7-code`, `deepseek-v4-pro`;")
    A("  **cheap:** `deepseek-v4-flash`, `qwen3.8-flash`; **vision:** `deepseek-v4-flash-vision-exp`.")
    A("- All reachable via `https://opencode.ai/zen/go/v1/chat/completions` with `OPENCODE_ZEN_API_KEY`.")
    A("")
    A("### 8.4 OpenRouter paid")
    A("- **Frontier:** `anthropic/claude-sonnet-*`, `openai/gpt-5.*`, `google/gemini-3.*`, `x-ai/grok-4.*`.")
    A("- **Value code:** `qwen/qwen3.*-coder`, `deepseek/deepseek-v3.*`, `moonshotai/kimi-k2.*`, `z-ai/glm-*`.")
    A("- Use where OpenCode Zen lacks a model; one API key for 400+ models.")
    A("")
    A("### 8.5 Free tier (OpenCode Zen + OpenRouter together)")
    A("Health-checked best picks (avoid the throttled ones):")
    A("")
    A("| Need | Primary | Fallbacks |")
    A("|---|---|---|")
    A("| Long-context reasoning / architecture | `nvidia/nemotron-3-super-120b-a12b:free` (OR) | `nvidia/nemotron-3-ultra-550b-a55b:free`, `thinkingmachines/inkling:free`, `nemotron-3.5-lightning-free` (Zen) |")
    A("| Fast general / discovery | `nvidia/nemotron-3.5-lightning:free` (OR) | `nemotron-3.5-lightning-free` (Zen), `openrouter/free` |")
    A("| Coding (tool use) | `cohere/north-mini-code:free` (OR) | `poolside/laguna-xs-2.1:free`, `ling-3.0-flash-fin-free` (Zen) |")
    A("| Structured specs/docs | `dots-studio/dots-3-note-preview:free` (OR) | `nex-agi/nex-n2.5-pro:free`, `nemotron-3.5-lightning-free` (Zen) |")
    A("| Reasoning/agentic loop | `nex-agi/nex-n2.5-pro:free` / `nex-n2.5-mini:free` (OR) | `nemotron-3.5-lightning-free` (Zen) |")
    A("| Vision / visual QA | `nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free` (OR) | `inclusionai/ling-3.0-flash-vl:free`, `google/gemma-4-31b-it:free` |")
    A("| Multilingual / finance | `inclusionai/ling-3.0-flash-vl:free` / `ling-3.0-flash-fin:free` (OR) | `mimo-v2.5-free` (Zen) |")
    A("| Universal catch-all | `openrouter/free` | `nemotron-3.5-lightning-free` (Zen) |")
    A("")
    A("**Throttled — avoid as primary (observed 429):** `mimo-v2.5-free`, `big-pickle` (Zen);")
    A("`poolside/laguna-s-2.1:free`, `google/gemma-4-31b-it:free` (OpenRouter).")
    A("")
    A("**Notes:** OpenCode Zen free models are heavily rate-limited; prefer OpenRouter free as")
    A("primary with Zen as cross-provider fallback. No Zen free model offers vision.")
    A("")
    A("## 9. How to apply")
    A("- Edit `config/model-tier.json` → `profiles.free-trial` (per-agent `model` + `fallback_models`)")
    A("  and the base `agents`/`stages` blocks for the **actual** tier.")
    A("- Select at runtime: `PIPELINE_MODEL_TIER=free-trial` or `run_pipeline.py --tier free-trial`.")
    A("- Keep every referenced model in the profile's `models` map so it resolves to the correct provider/endpoint.")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote", OUT, "| lines:", len(L))
    print("registry models:", len(reg), "| OpenRouter models:", len(or_models),
          "| zen models:", len(zen_ids), "| agents:", len(agents))


if __name__ == "__main__":
    main()
